components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: integer
          description: ID auto-generado del producto
        name:
          type: string
          description: Nombre del producto
        sku:
          type: string
          description: Código SKU único
        description:
          type: string
          description: Descripción del producto
        category_id:
          type: integer
          description: ID de la categoría asociada
        base_price:
          type: number
          description: Precio base de venta
        image_url:
          type: string
          description: URL de la imagen del producto
        min_stock:
          type: integer
          description: Stock mínimo para alertas
        perishable:
          type: boolean
          description: Indica si el producto es perecedero
        status:
          type: boolean
          description: Estado del producto
      example:
        product_id: 101
        name: "Leche"
        sku: "LCH-001"
        description: "Leche entera de 1 litro"
        category_id: 2
        base_price: 1.50
        min_stock: 20
        perishable: true
        status: true

paths:
  /product:
    get:
      summary: Obtener todos los productos
      tags: [Product]
      responses:
        200:
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto (con imagen opcional)
      tags: [Product]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - sku
                - category_id
                - base_price
              properties:
                name:
                  type: string
                sku:
                  type: string
                description:
                  type: string
                category_id:
                  type: integer
                base_price:
                  type: number
                min_stock:
                  type: integer
                perishable:
                  type: boolean
                image:
                  type: string
                  format: binary
                  description: Archivo de imagen del producto
      responses:
        201:
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                  data:
                    $ref: '#/components/schemas/Product'

  /product/{id}:
    get:
      summary: Obtener un producto por ID
      tags: [Product]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto
      responses:
        200:
          description: Producto encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado
    patch:
      summary: Actualizar un producto existente
      tags: [Product]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                sku:
                  type: string
                description:
                  type: string
                category_id:
                  type: integer
                base_price:
                  type: number
                min_stock:
                  type: integer
                perishable:
                  type: boolean
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Producto actualizado
    delete:
      summary: Eliminar permanentemente un producto
      tags: [Product]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto
      responses:
        200:
          description: Producto eliminado

  /product/category/{category_id}:
    get:
      summary: Obtener productos por categoría
      tags: [Product]
      parameters:
        - in: path
          name: category_id
          schema:
            type: integer
          required: true
          description: ID de la categoría
      responses:
        200:
          description: Lista de productos filtrada

  /product/{id}/deactivate:
    patch:
      summary: Desactivar un producto
      tags: [Product]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto
      responses:
        200:
          description: Producto desactivado

  /product/{id}/activate:
    patch:
      summary: Activar un producto
      tags: [Product]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto
      responses:
        200:
          description: Producto activado