export * from "./category.routes";
export * from "./depot.routes";
export * from "./movement.routes";
export * from "./product.routes";
export * from "./provider.routes";
export * from "./purchase.routes";
export * from "./rol.routes";
export * from "./type-payment.routes";
export * from "./user.routes";