export * from "./category.controller";
export * from "./depot.controller";
export * from "./movement.controller";
export * from "./rol.controller";
export * from "./product.controller";
export * from "./provider.controller";
export * from "./purchase.controller";
export * from "./type-payment.controller";
export * from "./user.controller";